### ISSUE TITLE
How to format "ratings"

### ISSUE THREAD

**Issue by carly-donahue** [PamixSun/DeLongUI#1]
Hello,

I am unsure of how to format my input data. Could you explain further what the input of the ratings matrix is asking for? I am not sure what "the ratings of one experiments" means and I've tried a few things, but cannot figure it out.

**Comment by Li-Jiren** [comment]
The instruction is quite confusing, I spent several hours to figure out how to use this tool. For anyone who want to use this tool in the future:

'one experiment' corresponds to one RUC curve (the prediction result of one model on one testing dataset). So, if you want two compare two RUC curves, then _K_=2.

X and Y means the number of positive and negative samples

_ratings_ is the predicted scores for each sample from the model. You can just use the probability.

For example, a testing dataset has 2 positive and 3 negative samples, then _spsizes_ should be [2; 3], and if you use probability as the score, _ratings_ of one good model and one bad model should be like [0.99 0.96 0.12 0.07 0.05; 0.6 0.7 0.43 0.34 0.45]
